Repository MuDuck-team/MuDuck, pull requests merged in 2023-03, with the labels that each got.

#62 [Feat] Main 페이지 구현
  client/src/routes/Main/MainPage.jsx
  client/src/routes/Main/PopularPlays.jsx
  client/src/routes/Main/PopularPosts.jsx
Labels: Frontend

#64 Maps api
  server/.gitignore
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/map/entity/Map.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/entity/RecommendPlace.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
  server/src/main/java/MuDuck/MuDuck/theater/controller/TheaterController.java
  server/src/main/java/MuDuck/MuDuck/theater/dto/TheaterDto.java
  server/src/main/java/MuDuck/MuDuck/theater/entitiy/Theater.java
  server/src/main/java/MuDuck/MuDuck/theater/mapper/TheaterMapper.java
  server/src/main/java/MuDuck/MuDuck/theater/repository/TheaterRepository.java
  server/src/main/java/MuDuck/MuDuck/theater/service/TheaterService.java
  server/src/main/resources/db/data.sql
  server/src/main/resources/static/docs/index.html
  server/src/test/java/MuDuck/MuDuck/theater/controller/TheaterControllerTest.java
  server/src/test/java/MuDuck/MuDuck/theater/repository/TheaterRepositoryTest.java
  server/src/test/java/MuDuck/MuDuck/theater/service/TheaterServiceTest.java
  server/src/test/java/MuDuck/MuDuck/utils/ApiDocumentUtils.java
Labels: Backend

#63 Board api
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/actor/entity/Actor.java
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
  server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/category/entity/Category.java
  server/src/main/java/MuDuck/MuDuck/category/joinTable/BoardCategory.java
  server/src/main/java/MuDuck/MuDuck/comment/entity/Comment.java
  server/src/main/java/MuDuck/MuDuck/map/entity/Map.java
  server/src/main/java/MuDuck/MuDuck/member/entity/Member.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/noticeboard/dto/NoticeBoardDto.java
  server/src/main/java/MuDuck/MuDuck/noticeboard/entity/NoticeBoard.java
  server/src/main/java/MuDuck/MuDuck/noticeboard/mapper/NoticeBoardMapper.java
  server/src/main/java/MuDuck/MuDuck/noticeboard/repository/NoticeBoardRepository.java
  server/src/main/java/MuDuck/MuDuck/noticeboard/service/NoticeBoardService.java
  server/src/main/java/MuDuck/MuDuck/response/BoardMultipleResponse.java
  server/src/main/java/MuDuck/MuDuck/response/PageInfo.java
  server/src/main/java/MuDuck/MuDuck/utils/Chrono.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#65 Feature/update add
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/DropDown.jsx
  client/src/components/Editors.jsx
  client/src/components/Input.jsx
  client/src/index.jsx
  client/src/routes/Add/AddPage.jsx
  client/src/routes/NoticeAdd/NoticeAddPage.jsx
  client/src/routes/NoticeEdit/NoticeEditPage.jsx
  client/src/routes/PostAdd/PostAddPage.jsx
  client/src/routes/PostEdit/PostEditPage.jsx
  client/src/routes/Update/UpdatePage.jsx
Labels: Frontend

#66 [Design] Mypage UI 구현
  client/src/routes/Mypage/ContentData.js
  client/src/routes/Mypage/MyPage.jsx
Labels: Frontend

#67 [Design] 로그인 관련 페이지 레이아웃 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/assets/kakaoStart.png
  client/src/components/Editors.jsx
  client/src/components/Header.jsx
  client/src/components/Input.jsx
  client/src/components/KakaoLoginBtn.jsx
  client/src/components/ProfileImage/ProfileImg.jsx
  client/src/components/ProfileImage/ProfileImgSetter.jsx
  client/src/components/ProfileImage/ProfileUploader.js
  client/src/components/ProfileImage/index.js
  client/src/index.jsx
  client/src/routes/AdminLogin/AdminLoginPage.jsx
  client/src/routes/Login/LoginPage.jsx
  client/src/routes/Myinfo/MyinfoPage.jsx
  client/src/routes/Signup/SingupPage.jsx
Labels: Frontend

#70 [Fix] 파일 import path 수정
  client/src/components/Header.jsx
  client/src/components/ProfileImage/index.js
  client/src/routes/Mypage/MyPage.jsx
Labels: Frontend

#69 Feature/posts notices
  client/src/components/DropDown.jsx
  client/src/index.jsx
  client/src/routes/Notices/NoticesPage.jsx
  client/src/routes/Posts/PostsPage.jsx
Labels: Frontend

#75 [Design] favicon 타이틀변경
  client/public/favicon.ico
  client/public/index.html
  client/public/muduckIcon.png
Labels: Frontend

#73 BoardAPI 1번, 4번, 8번 구현 완료
  server/scripts/deploy.sh
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/category/dto/CategoryDto.java
  server/src/main/java/MuDuck/MuDuck/category/entity/Category.java
  server/src/main/java/MuDuck/MuDuck/category/mapper/CategoryMapper.java
  server/src/main/java/MuDuck/MuDuck/category/repository/CategoryRepository.java
  server/src/main/java/MuDuck/MuDuck/category/service/CategoryService.java
  server/src/main/java/MuDuck/MuDuck/response/BoardMultipleResponse.java
  server/src/main/java/MuDuck/MuDuck/response/CategoryMultipleResponse.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#71 [Design] 공지사항 상세 페이지 UI 구현
  client/src/components/MeatballsMenu.jsx
  client/src/components/PostInfo.jsx
  client/src/routes/Notice/Notice.jsx
Labels: Frontend

#72 [Design] 공연 목록 페이지 UI 구현
  client/src/components/ImageCard.jsx
  client/src/routes/Plays/PlayData.js
  client/src/routes/Plays/PlaysPage.jsx
Labels: Frontend

#87 [Design] ErrorPage 디자인 추가
  client/src/routes/Error/ErrorPage.jsx
Labels: Frontend

#88 [Feat/Fix] OAuth2 로그인 핸들러 수정 및 액세스 토큰 재발급 로직 구현
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
  server/src/main/java/MuDuck/MuDuck/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/MuDuck/MuDuck/auth/jwt/entrypoint/MemberAuthenticationEntryPoint.java
  server/src/main/java/MuDuck/MuDuck/auth/jwt/filter/JwtExceptionFilter.java
  server/src/main/java/MuDuck/MuDuck/auth/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/MuDuck/MuDuck/auth/utils/ExceptionResponse.java
  server/src/main/java/MuDuck/MuDuck/member/entity/Member.java
  server/src/main/java/MuDuck/MuDuck/member/repository/MemberRepository.java
  server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
  server/src/main/java/MuDuck/MuDuck/token/dto/AccessTokenDto.java
  server/src/main/java/MuDuck/MuDuck/token/service/RefreshTokenService.java
  server/src/main/java/MuDuck/MuDuck/utils/CustomBeanUtils.java
  server/src/main/resources/db/data.sql
Labels: Backend

#86 게시판 API 명세서 6번, 7번 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/auth/jwt/filter/JwtExceptionFilter.java
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
  server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/boardLike/entity/BoardLike.java
  server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/dto/CommentDto.java
  server/src/main/java/MuDuck/MuDuck/comment/entity/Comment.java
  server/src/main/java/MuDuck/MuDuck/comment/mapper/CommentMapper.java
  server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/member/dto/MemberDto.java
  server/src/main/java/MuDuck/MuDuck/member/entity/Member.java
  server/src/main/java/MuDuck/MuDuck/member/repository/MemberRepository.java
  server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java
  server/src/main/java/MuDuck/MuDuck/response/BoardContentMultipleResponse.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#90 [Feat/Fix] 회원 컨트롤러 API 구현 및 ErrorResponse 추가 & OAuth2 핸들러 URL 변경
  server/src/main/java/MuDuck/MuDuck/advice/GlobalExceptionAdvice.java
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/member/controller/MemberController.java
  server/src/main/java/MuDuck/MuDuck/member/dto/MemberDto.java
  server/src/main/java/MuDuck/MuDuck/response/ErrorResponse.java
  server/src/main/java/MuDuck/MuDuck/token/service/RefreshTokenService.java
Labels: Backend

#91 [Fix] 회원정보수정API 수정
  server/src/main/java/MuDuck/MuDuck/member/controller/MemberController.java
  server/src/main/java/MuDuck/MuDuck/member/mapper/MemberMapper.java
  server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java
Labels: Backend

#92 [Feat] 게시판 API 명세서 9번 #36
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
  server/src/main/java/MuDuck/MuDuck/boardCategory/service/BoardCategoryService.java
  server/src/main/resources/application.yml
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#93 [Feat] 공연상세 페이지 구현 (추후보완예정)
  client/package-lock.json
  client/package.json
  client/src/components/Cards.jsx
  client/src/components/Header.jsx
  client/src/components/ProfileImage/ProfileImg.jsx
  client/src/routes/Play/Mapbox.jsx
  client/src/routes/Play/PlayPage.jsx
  client/src/styles/GlobalStyle.js
Labels: Frontend

#94 [Feat] Musical API #1~4 구현 및 TEST 확인 #38
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/actor/entity/Actor.java
  server/src/main/java/MuDuck/MuDuck/actor/repository/ActorRepository.java
  server/src/main/java/MuDuck/MuDuck/actor/service/ActorService.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/java/MuDuck/MuDuck/response/ErrorResponse.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/data.sql
  server/src/main/resources/static/docs/index.html
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
  server/src/test/java/MuDuck/MuDuck/musical/service/MusicalServiceMockTest.java
Labels: Backend

#95 [Feat] 커뮤니티 상세 페이지 API 연결
  client/src/components/WriterInfo.jsx
  client/src/index.jsx
  client/src/routes/Post/CommentList.jsx
  client/src/routes/Post/PostData.js
  client/src/routes/Post/PostPage.jsx
Labels: Frontend

#96 [Feat/Fix] 회원 정보 수정 API 오류 해결 및 memberController 테스트코드 작성 및 custom snippet 구현
  server/.gitignore
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/auth/handler/MemberLogoutSuccessHandler.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/member/controller/MemberController.java
  server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java
  server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
  server/src/test/java/MuDuck/MuDuck/member/controller/MemberControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: documentation, Backend

#99 [Fix] request-fields snippet 수정
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: Backend

#102 [Feat/Fix] 주변장소추천 , 지도 repository 생성 및 security cors 설정 수정, exceptiohandler 추가
  server/src/main/java/MuDuck/MuDuck/advice/GlobalExceptionAdvice.java
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
  server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
  server/src/main/resources/db/data.sql
Labels: Backend

#104 [Fix] Merge 하던 중 Conflict 파일을 잘못 해결해서 생긴 오류 수정 #36
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
Labels: Backend

#105 [Fix] 더미데이터 추가 및 테스트를 위한 cookie 설정 변경
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/resources/db/data.sql
Labels: Backend

#107 [Fix] cookie 설정 원래 상태로 변경 및 액세스토큰 유효기간 변경
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/resources/application.yml
Labels: Backend

#108 [Feat] 카카오로그인 기능구현
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/api/customAxios.js
  client/src/components/Header.jsx
  client/src/components/KakaoLoginBtn.jsx
  client/src/components/ProfileImage/ProfileUploader.js
  client/src/index.jsx
  client/src/recoil/userAtom.js
  client/src/routes/Myinfo/MyinfoPage.jsx
  client/src/routes/OauthRedirect/OauthRedirectPage.jsx
Labels: Frontend

#109 [Refact] 게시글 등록 API responseBody 형태 변경
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#110 [Fix] mapRepository 수정및 더미데이터 수정 security cors 설정 변경
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/main/resources/db/data.sql
Labels: Backend

#112 [Refact] 댓글 post responseBody를 HttpStatus로만 응답하도록 변경 또한 해당 사항에 맞게 Controller Test 코드 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#113 [Refact] 대댓글 post responseBody를 HttpStatus로만 응답하도록 변경 관련 Controller Test 작성
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#114 [Refact/Test] 댓글 delete 코드 responseBody를 HttpStatus로만 응답하게 변경 및 테스트 코드 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#97 [Frontend] Feature/nearby page
  client/public/index.html
  client/src/components/Cards.jsx
  client/src/components/Input.jsx
  client/src/components/StarRating.jsx
  client/src/index.jsx
  client/src/routes/Nearby/MyMap.jsx
  client/src/routes/Nearby/MyMapContainer.jsx
  client/src/routes/Nearby/NearbyPage.jsx
  client/src/styles/variables.js
  client/src/utile/changeObjKeys.js
Labels: Frontend

#117 [Feat] 모바일 사이즈에서 탭클릭시 헤더토글 닫기 기능 추가
  client/src/components/Header.jsx
Labels: Frontend

#118 [Frontend] Feature/posts get data 구현
  client/public/index.html
  client/src/components/Cards.jsx
  client/src/routes/Posts/PostsPage.jsx
Labels: Frontend

#120 [Feat] 게시글 좋아요 기능 구현 및 Controller Test 구현 완료
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/boardLike/entity/BoardLike.java
  server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#122 [Feat/Fix] 지도정보 조회 API 코드 구현 및 테스트 코드 구현 & GroupCode 수정 & 더미 데이터 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/map/controller/MapController.java
  server/src/main/java/MuDuck/MuDuck/map/dto/AvgDto.java
  server/src/main/java/MuDuck/MuDuck/map/entity/AvgEntity.java
  server/src/main/java/MuDuck/MuDuck/map/groupcode/GroupCode.java
  server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/map/controller/MapControllerTest.java
Labels: documentation, Backend

#119 [Feat/Fix] Musical Api #5 Controller구현 및 Test 케이스 작성, category 테이블 생성 쿼리 변경 및 쿼리 순서 변경 #38
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/java/MuDuck/MuDuck/theater/dto/TheaterDto.java
  server/src/main/java/MuDuck/MuDuck/theater/mapper/TheaterMapper.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#123 [Feat] Musical Api #7 Controller구현 및 Test 케이스 작성 #38
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalPatchDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalPostDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalResponseDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/resources/application.yml
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#124 [Feat/Test] 게시글 좋아요 삭제 기능 구현 및 Controller Test 진행
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
  server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/dto/CommentDto.java
  server/src/main/java/MuDuck/MuDuck/comment/mapper/CommentMapper.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java
Labels: Backend

#125 [Fix] Musical Api #7 Controller구현 및 Test 케이스 작성 #38
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/musical/dto/Category.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalBoards.java
  server/src/test/java/MuDuck/MuDuck/MuDuckApplicationTests.java
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#121 [Feat] 커뮤니티 상세 페이지 댓글 등록/삭제 기능 구현
  client/src/components/Button.jsx
  client/src/components/WriterInfo.jsx
  client/src/index.jsx
  client/src/routes/Post/CommentList.jsx
  client/src/routes/Post/PostPage.jsx
Labels: Frontend

#126 [Feat] Feature/post add update
  client/src/components/Editors.jsx
  client/src/index.jsx
  client/src/routes/Nearby/NearbyPage.jsx
  client/src/routes/PostAdd/PostAddPage.jsx
  client/src/routes/PostEdit/PostEditPage.jsx
Labels: Frontend

#127 [Fix] Feature/edit map warning
  client/public/index.html
  client/src/routes/Nearby/MyMap.jsx
Labels: Frontend

#130 [Feat] mypage 프로필사진 닉네임 변경기능 구현
  client/src/components/ProfileImage/ProfileImgSetter.jsx
  client/src/routes/Myinfo/MyinfoPage.jsx
  client/src/routes/Mypage/MyPage.jsx
Labels: Frontend

#132 [Feat] 헤더에서 자신의 페이지를 눌렀을 때 선택한 드롭다운 값이 초기화되게 함
  client/src/routes/Posts/PostsPage.jsx
Labels: Frontend

#133 [FIX] Musical Api #5, #7 관련 버그 수정 #38
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/actor/dto/ActorDto.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/entity/ActorsEntity.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/mapper/ActorMusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/repository/ActorMusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/service/ActorMusicalService.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/CategoryDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalBoardsDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Category.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/MusicalBoards.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/MuDuckApplicationTests.java
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
  server/src/test/java/MuDuck/MuDuck/musical/service/MusicalServiceMockTest.java
Labels: Backend

#136 [Feat/Test] 메인페이지 데일리, 위클리 인기글 기능 구현 및 Controller Test 진행 #134
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/mainPage/controller/MainPageController.java
  server/src/main/java/MuDuck/MuDuck/mainPage/dto/MainPageDto.java
  server/src/main/java/MuDuck/MuDuck/mainPage/mapper/MainPageMapper.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/mainPage/controller/MainPageControllerTest.java
Labels: Backend

#139 [Feat/Fix] MyPage 내가 쓴 글 가져오기, 내가 좋아요 누른 글 가져오기 구현 완료. 카테고리네임에 값을 넣어서 게시글 목록 가져올 때, 삭제된 게시글도 가져오는 에러 수정 완료.
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
  server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
  server/src/main/java/MuDuck/MuDuck/myPage/dto/MyPageDto.java
  server/src/main/java/MuDuck/MuDuck/myPage/mapper/MyPageMapper.java
  server/src/main/resources/db/data.sql
Labels: Backend

#138 [Feat/Fix] 한줄평과 별점 등록 API 구현및 테스트코드 구현 & 더미데이터 좌표 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
  server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
  server/src/main/java/MuDuck/MuDuck/map/dto/MapDto.java
  server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
  server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/dto/RecommendPlaceDto.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/mapper/RecommendPlaceMapper.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
  server/src/main/java/MuDuck/MuDuck/theater/service/TheaterService.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/member/controller/MemberControllerTest.java
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
  server/src/test/java/MuDuck/MuDuck/theater/controller/TheaterControllerTest.java
Labels: documentation, Backend

#140 [Feat/Test] 내가 쓴 댓글 가져오기 기능 구현, MyPage 관련 Controller Test 완료
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
  server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
  server/src/main/java/MuDuck/MuDuck/myPage/dto/MyPageDto.java
  server/src/main/java/MuDuck/MuDuck/myPage/mapper/MyPageMapper.java
  server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java
Labels: Backend

#141 [FEAT/FIX] Musical Api #6 Controller구현 완료 및 테스트코드 작성 중, #7 Response추가 #38
  server/src/main/java/MuDuck/MuDuck/actor/mapper/ActorMapper.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/entity/ActorsEntity.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/entity/MusicalEntity.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/mapper/ActorMusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/repository/ActorMusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/service/ActorMusicalService.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusicalEntity.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/MusicalBoards.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Response.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#142 [Feat/Fix] 평점과 한줄평 조회API 구현 및 테스트 코드 구현 & rest docs 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
  server/src/test/java/MuDuck/MuDuck/map/controller/MapControllerTest.java
  server/src/test/java/MuDuck/MuDuck/member/controller/MemberControllerTest.java
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
Labels: documentation, Backend

#143 [Fix] 마이페이지 기능에 페이지네이션 적용 #134
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
  server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
  server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
  server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
  server/src/main/java/MuDuck/MuDuck/response/MyPageBoardMultipleResponse.java
  server/src/main/java/MuDuck/MuDuck/response/MyPageCommentsMultipleResponse.java
Labels: Backend

#135 [Feat] 공연 목록 페이지 기능 구현
  client/src/components/ImageCard.jsx
  client/src/index.jsx
  client/src/routes/Plays/PlayData.js
  client/src/routes/Plays/PlaysPage.jsx
Labels: Frontend

#146 [Feat] 커뮤니티 상세 페이지 기능 구현
  client/src/components/Input.jsx
  client/src/components/MeatballsMenu.jsx
  client/src/components/WriterInfo.jsx
  client/src/routes/Post/CommentList.jsx
  client/src/routes/Post/PostPage.jsx
Labels: Frontend

#145 [Feat] 공연상세페이지 API 연결
  client/src/api/muduckApi.js
  client/src/components/Cards.jsx
  client/src/index.jsx
  client/src/routes/Play/AboutMusical.jsx
  client/src/routes/Play/Mapbox.jsx
  client/src/routes/Play/PlayNotFoundPage.jsx
  client/src/routes/Play/PlayPage.jsx
Labels: Frontend

#147 [Feat] 평점 및 한줄평 수정 API 구현 및 테스트 코드 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/dto/RecommendPlaceDto.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/mapper/RecommendPlaceMapper.java
  server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
Labels: documentation, Backend

#148 [Test] 마이페이지 페이지네이션 구현에 따른 Controller Test 변경 #134
  server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java
Labels: Backend

#152 [FEAT/FIX] MainPage Api #3 Controller구현, 데모데이터 수정 중
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/actor/dto/ActorDto.java
  server/src/main/java/MuDuck/MuDuck/actor/dto/ActorPatchDto.java
  server/src/main/java/MuDuck/MuDuck/actor/dto/ActorResponseDto.java
  server/src/main/java/MuDuck/MuDuck/actor/mapper/ActorMapper.java
  server/src/main/java/MuDuck/MuDuck/actorMusical/service/ActorMusicalService.java
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/mainPage/controller/MainPageController.java
  server/src/main/java/MuDuck/MuDuck/mainPage/dto/MainPageDto.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalBoardsDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/MusicalBoards.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/resources/db/data.sql
  server/src/test/java/MuDuck/MuDuck/mainPage/controller/MainPageControllerTest.java
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#150 [Design] 카카오로그인선택시 업로드아이콘 배경 어둡게 처리
  client/src/components/ProfileImage/ProfileImgSetter.jsx
  client/src/routes/Myinfo/MyinfoPage.jsx
Labels: Frontend

#153 [Fix] 마이페이지 내가 쓴 댓글 가져오기 기능에서 responseBody에 id 추가 및 삭제된 게시글의 댓글이 가져와지는 오류 수정 #134
  server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
  server/src/main/java/MuDuck/MuDuck/myPage/dto/MyPageDto.java
  server/src/main/java/MuDuck/MuDuck/myPage/mapper/MyPageMapper.java
  server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java
Labels: Backend

#154 [FIX] Musical Api #7 이슈 수정 #38
  server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
  server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/resources/db/data.sql
Labels: Backend

#155 [TEST] 평점 한줄평exception 테스트 코드 구현
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
Labels: Backend

#158 [Style] 공연상세 게시판 관련 응답데이터 필드명변경에 따른 조정
  client/src/routes/Play/PlayPage.jsx
Labels: Frontend

#157 [Feat] 마이페이지 기능 구현
  client/src/components/Cards.jsx
  client/src/components/Loading.jsx
  client/src/routes/Mypage/MyCommentList.jsx
  client/src/routes/Mypage/MyInformation.jsx
  client/src/routes/Mypage/MyLikePostList.jsx
  client/src/routes/Mypage/MyPage.jsx
  client/src/routes/Mypage/MyPostList.jsx
Labels: Frontend

#149 [Feat] Feature/nearby page
  client/src/components/DropDown.jsx
  client/src/routes/Nearby/MyMap.jsx
  client/src/routes/Nearby/MyMapContainer.jsx
  client/src/routes/Nearby/NearbyPage.jsx
  client/src/utile/changeObjKeys.js
Labels: Frontend

#162 [Chore] 로그인페이지 원본으로 복구
  client/src/routes/Login/LoginPage.jsx
Labels: Frontend

#163 Feature/nearby page
  client/src/api/muduckApi.js
  client/src/components/Map/Map.jsx
  client/src/components/Map/MapContainer.jsx
  client/src/components/StarRating.jsx
  client/src/routes/Nearby/NearbyPage.jsx
  client/src/routes/Play/PlayPage.jsx
  client/src/routes/Posts/PostsPage.jsx
Labels: Frontend

#160 [Feat] 메인 페이지 기능 구현
  client/src/api/muduckApi.js
  client/src/index.jsx
  client/src/routes/Main/BannersData.js
  client/src/routes/Main/MainPage.jsx
  client/src/routes/Main/PopularPlays.jsx
  client/src/routes/Main/PopularPosts.jsx
  client/src/routes/Mypage/ContentData.js
Labels: Frontend

#168 [Fix] 페이지 첫 진입시 헤더 로그인상태로 되는 버그 수정
  client/src/components/Header.jsx
  client/src/routes/OauthRedirect/OauthRedirectPage.jsx
Labels: Frontend

#169 [Design] 컴포넌트 디자인 조정
  client/src/components/DropDown.jsx
  client/src/components/Modal/Modal.jsx
  client/src/components/Modal/ModalExample.jsx
  client/src/components/Modal/ModalPortal.jsx
  client/src/styles/GlobalStyle.js
Labels: Frontend

#172 [Fix] 헤더 새로고침시 유저정보 변경되는 버그 수정
  client/src/components/Header.jsx
  client/src/routes/OauthRedirect/OauthRedirectPage.jsx
Labels: bug, Frontend

#173 [Feat] 로딩 & 스크롤 최상단 이동 기능 구현
  client/src/components/ScrollToTop.jsx
  client/src/routes/Root.jsx
Labels: Frontend

#174 [Fix] 평점 및 한줄평 조회API 수정 및 테스트코드 수정
  server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
Labels: Backend

#175 [Fix] 평점 및 한줄평 조회 테스트코드 수정
  server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
Labels: Backend

#176 [Fix] 헤더 로그인 새로고침해야 반영되는 현상 수정
  client/src/components/Header.jsx
Labels: Frontend

#177 [Design] Loading Spinner 크기 조정
  client/src/components/Loading.jsx
Labels: Frontend

#178 [Fix] 로그인 여부확인 헤더에서 Root로 변경
  client/src/components/Header.jsx
  client/src/routes/Root.jsx
Labels: bug, Frontend

#159 [FIX] Actor엔티티 조정 및 데모데이터 작성 #38
  server/src/main/java/MuDuck/MuDuck/actor/entity/Actor.java
  server/src/main/resources/db/data.sql
Labels: Backend

#184 [Fix] mapRepository Mysql에 맞게 쿼리문 수정
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/test/java/MuDuck/MuDuck/theater/repository/TheaterRepositoryTest.java
Labels: Backend

#185 [Design] 공지사항 목록 레이아웃 조정
  client/src/index.jsx
  client/src/routes/Notice/NoticePage.jsx
  client/src/routes/Notices/NoticesPage.jsx
Labels: Frontend

#186 [Design] ImageCard 배우 명단 출력 제거
  client/src/components/ImageCard.jsx
  client/src/routes/Main/PopularPlays.jsx
  client/src/routes/Plays/PlaysPage.jsx
Labels: Frontend

#188 [Fix] 지도 관련 mapper 수정
  server/src/main/java/MuDuck/MuDuck/map/entity/AvgEntity.java
  server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java
Labels: Backend

#189 [BE] Musical Api #6,7 / MainPage Api #3 Controller 테스트 코드 작성 #38
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/MuDuck/MuDuck/actorMusical/mapper/ActorMusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
  server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
  server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
  server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
  server/src/main/resources/application.yml
  server/src/test/java/MuDuck/MuDuck/mainPage/controller/MainPageControllerTest.java
  server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
Labels: Backend

#195 [F ix] 커뮤니티 상세 페이지 개선
  client/src/components/WriterInfo.jsx
  client/src/routes/Mypage/MyInformation.jsx
  client/src/routes/Post/CommentList.jsx
  client/src/routes/Post/PostPage.jsx
  client/src/routes/PostAdd/PostAddPage.jsx
Labels: Frontend

#196 [Design] 회원가입페이지삭제
  client/src/assets/kakaoMid.png
  client/src/assets/kakaoStart.png
  client/src/components/KakaoLoginBtn.jsx
  client/src/index.jsx
  client/src/routes/Login/LoginPage.jsx
  client/src/routes/Signup/SingupPage.jsx
Labels: Frontend

#197 [Design] 서비스 디자인 개선
  client/src/components/Editors.jsx
  client/src/components/MeatballsMenu.jsx
  client/src/routes/Main/MainPage.jsx
  client/src/routes/Plays/PlaysPage.jsx
  client/src/styles/GlobalStyle.js
Labels: Frontend

#200 [Design] 헤더 액티브 css 추가
  client/src/components/Header.jsx
Labels: Frontend

#202 [Design] 공연상세페이지 세부 디테일 수정사항 개선
  client/src/routes/Play/AboutMusical.jsx
  client/src/routes/Play/PlayPage.jsx
Labels: Frontend

#206 [Design] toastify UI 적용
  client/src/routes/Myinfo/MyinfoPage.jsx
  client/src/routes/Root.jsx
Labels: Frontend

#207 [Design] 토스트디자인 세부설정
  client/src/routes/Myinfo/MyinfoPage.jsx
  client/src/routes/Root.jsx
Labels: Frontend

#209 [Fix] 일부유저에게 게시글작성 TextArea 높이가 변경되는 현상수정
  client/src/components/Editors.jsx
  client/src/components/Input.jsx
Labels: Frontend

#212 [FIX] 특정 작품 조회시 삭제된 관련 게시글 나오는 버그 수정 및 data.sql 이미지 관련 수정
  server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
  server/src/main/resources/db/data.sql
Labels: Backend

#214 [Fix] mapRepository 쿼리문 수정 & 더미데이터 변경
  server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
  server/src/main/resources/db/data.sql
Labels: Backend

#217 [Refactor] Feature/near by refactoring
  client/src/components/Map/Map.jsx
  client/src/routes/Nearby/NearbyPage.jsx
  client/src/routes/Play/AboutMusical.jsx
  client/src/routes/Root.jsx
Labels: Frontend

#218 [Fix] Feature/near by refactoring
  client/src/routes/Nearby/NearbyPage.jsx
Labels: Frontend

#220 [Fix] security antMatchers 수정&로그인 성공 실패 핸들러 수정& yml 수정
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationFailureHandler.java
  server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/MuDuck/MuDuck/member/dto/MemberDto.java
  server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/main/resources/db/data.sql
Labels: Backend

#219 antMatchers 추가
  server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
Labels: Backend

#221 [Fix] yml 수정
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: Backend

#223 [Fix] yml 환경변수 설정
  server/src/test/resources/application-local.yml
  server/src/test/resources/application.yml
Labels: Backend
